name: Sync to Main Repo
on:
  push:
    branches: [ main ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Pushes to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'tenoenc'
          destination-repository-name: 'algorithm-solutions'
          target-directory: 'LeetCode'
          user-email: 'tenoenc@gmail.com'
          target-branch: main
